version: '3'

networks:
  my_network:
    external: true

services:

  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    networks:
      - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=Willie75
      - MYSQL_PASSWORD=Willie75
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=marcoz
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    build: .
    networks:
      - my_network
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=marcoz
      - MYSQL_PASSWORD=Willie75
      - NEXTCLOUD_ADMIN_USER=marcoz
      - NEXTCLOUD_ADMIN_PASSWORD=Willie75
      - REDIS_HOST=redis
    volumes:
      - nextcloud:/var/www/html

  redis:
    image: redis
    container_name: nextcloud_redis
    restart: always
    networks:
      - my_network

volumes:
  nextcloud:
  db:
