version: '3'

networks:
  my_network:
    external: true

services:

  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    networks:
      - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    build: .
    networks:
      - my_network
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
    volumes:
      - nextcloud:/var/www/html



volumes:
  nextcloud:
  db: