version: '3'

services:


  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Willie75
      - MYSQL_PASSWORD=Willie75
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=marcoz
    volumes:
      - db:/var/lib/mysql


  nextcloud1:
    image: nextcloud
    container_name: nextcloud1
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=marcoz
      - MYSQL_PASSWORD=Willie75
      - NEXTCLOUD_ADMIN_USER=marcoz
      - NEXTCLOUD_ADMIN_PASSWORD=Willie75
      - REDIS_HOST=redis
    volumes:
      - nextcloud:/var/www/html


  redis:
    image: redis
    container_name: nextcloud_redis
    restart: always

volumes:
  nextcloud:
  db: